### ISSUE TITLE
Some ePub files can’t be opened

### ISSUE THREAD

**Issue by anasram** [mate-desktop/atril#196]
I’ve been trying to recompress the content of [this ePub file](http://www1.hft-leipzig.de/graetzer/ebooktest/_IDPF_Samples/epub30-spec.epub) and open it using Atril 1.12.2-1+rosa, like this:

```
zip -r8 'my-eBook.epub' 'META-INF' 'EPUB' 'mimetype'
atril 'my-eBook.epub'
```
and here’s the result:

![atril](https://cloud.githubusercontent.com/assets/12219238/14963995/07a67e9a-10af-11e6-9615-270a4e87a004.png)

…although the original ePub file works fine using Atril.

The question is:
* Is this a bug in Atril itself?
* or: do I miss the right way to generate a valid ePub file from its resources *manually* under GNU/Linux command line?

**Comment by rootAvish** [comment]
> or: do I miss the right way to generate a valid ePub file from its resources manually under GNU/Linux command line?

The deal with this is that Atril performs a MIME type check to decide which backend to use for a certain document. The MIME type on this is most likely wrong(I don't remember what it's supposed to be exactly, probably document/epub), so even if you generate an epub with a valid manifest, the MIME type being wrong results in not finding a valid backend for the same, and hence the error message. I recommend use a proper epub generator such as the one provided by Calibre rather than just zipping the archive.

Sidenote: even if the mimetype is valid in the "mimetype" file, the MIME type used for the check is the one returned by the OS, which in this case is "application/zip".

**Comment by anasram** [comment]
The original file works fine on Atril, and I did not touch any of its content, including `mimetype` file when I recompressed it, so, `mimetype` file is still as is in both cases: the original and the recompressed ePub files.
I suppose the problem comes only from the compression method.

**Comment by rootAvish** [comment]
> I suppose the problem comes only from the compression method.

Right. That was the point I was trying to convey but I tend to ramble on about stuff, sorry about that. Like I said in my sidenote, the mimetype in the mimetype file does not matter till Atril actually knows that it's an epub. It's just used as a sanity check. When you compress using `zip`, the mimetype as recognized by the OS(or your file manager) is set to `application/zip`. It is this mimetype returned on probing the OS that is used to call the epub backend, not the one in the mimetype file.

**Comment by monsta** [comment]
@rootAvish: so I guess we can close it then?

**Comment by anasram** [comment]
> do I miss the right way to generate a valid ePub file from its resources manually under GNU/Linux command line?

Yes. The right way is:
```
zip -X0 'my-ebook.epub' 'mimetype'
zip -Xr8 'my-ebook.epub' 'META-INF/' 'OEBPS/'
atril 'my-ebook.epub'
```
@monsta and now we can close it :)

**Comment by monsta** [comment]
Cool :smile:
