### ISSUE TITLE
Bookmark features

### ISSUE THREAD

**Issue by startatlinux** [mate-desktop/atril#220]
**Hi**
As someone who reads a lot pdf files, books and stuff I often VERY often tend to bookmark pages.
While it is very easy to bookmark with Ctrl+D without even asking you a question (which I like)
It doesn't offer you two main things, first its naming the bookmark and 2nd is I can't delete it, at least I don't know how to. After adding 5+ bookmarks it gets confusing what was that I bookmarked. 

![screenshot at 2016-08-28 03 41 20](https://cloud.githubusercontent.com/assets/21280641/18034173/519aa452-6d36-11e6-84ac-93f612108267.png)

**So adding features like this:**

**-** When opening the bookmarks menu there should be 2 small icons 1 for naming bookmark and 2nd one for deleting the bookmark (a small x by the page number)

**-**  It would be also nice if opening a new pdf would open it in a new tab instead of a new window

Thats it for now :D

If these features are already there I apologize since I am using mate for couple weeks, it is awesome and I am going to stick with it, greetings
##

**Comment by monsta** [comment]
Renaming and deleting bookmarks is possible in Atril by now.

**Comment by jfcaron3** [comment]
In what version did renaming & deleting bookmarks arrive?  Ubuntu MATE (current LTS version) has 1.20.1 and I'm not sure if I should have it.

**Comment by dre2004** [comment]
I have version 1.24 and it still doesn't appear to support renaming or deleting bookmarks

**Comment by imrejonk** [comment]
The feature is available in Atril 1.26 (and if I'm reading the NEWS file correctly, it has been since 1.10), but I've found the UI to be a bit confusing. Adding bookmarks is easy using the Bookmarks option in the top menu bar. However, renaming or deleting a bookmark is a bit more involved:

1. Enable the side pane (if it isn't already) using View -> Side Pane.
2. Click the side pane selector drop-down at the top of the side pane and select Bookmarks.
3. Here you can add and remove bookmarks using the buttons at the bottom. Renaming a bookmark can be done by double-clicking on the bookmark, or using the context menu (click on the bookmark using your secondary mouse button).
