### ISSUE TITLE
Grey background in full screen Atril 

### ISSUE THREAD

**Issue by jEsuSdA** [mate-desktop/atril#232]
Hi!

When you open a PDF in Atril pdf viewer and you put it on full screen, the background is set as grey (the main background color for windows) instead black (the common color used in these cases by other apps).

Here you can see Evince in full screen:
![724a0134-adaf-11e6-9a3c-da387906b2ec](https://cloud.githubusercontent.com/assets/5833446/20438421/e0f4385e-adb7-11e6-8e46-0a54131cff27.png)

And here the same PDF in Atril:

![724af3b4-adaf-11e6-8395-7c89653e5ba6](https://cloud.githubusercontent.com/assets/5833446/20438425/e39a057a-adb7-11e6-8246-5269debbb97a.png)

Thank you so much for you job. ;)

**Comment by andyboeh** [comment]
Same problem for me, although the background is white. The same happens when pressing "b" on the keyboard: The screen goes white instead of black!

**Comment by computerix** [comment]
The problem is specific to gtk-3, it does not occur in gtk-2 (at least for me).

And it is much worse here: In fullscreen mode, the background to the left and right of the document's pages is set to the background color used in menues, dialogs etc., which is not grey in my theme, but #EBE5BC, i.e. some kind of yellow!
Using the dialog background color is definitely wrong,
I think black or the text foreground color should be used.

To fix that temporarily:
What needs to be added to the gtk theme's .css files to specifically set the background color of atril's fullscreen mode?

**Comment by raveit65** [comment]
Are you talking about presentation-mode?

**Comment by jEsuSdA** [comment]
Yes. When F5 key presed. ;)

**Comment by raveit65** [comment]
Ok, i will look into it.

**Comment by raveit65** [comment]
Pull request is done.
