### ISSUE TITLE
atril reports a segmentation fault when the user runs it by itself and try to change parameters.

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/atril#357]
#### Expected behaviour

The user should be able to change the parameters and have defaults the way they like. 

#### Actual behaviour

It segfaults . 

#### Steps to reproduce the behaviour

1. $ atril
2. Click on View > Zoom in

Just there, it puts a segmentation fault.

#### MATE general version

1.20.4-2

#### Package version

1.20.3-1

#### Linux Distribution

Debian testing (buster)

#### link to downstream report of your Distribution

https://bugs.debian.org/921325
[gdb-atril.txt](https://github.com/mate-desktop/atril/files/2827207/gdb-atril.txt)

**Comment by reubengreen73** [comment]
I have submitted pull requests for changes to fix this on both the 1.20 and master branches (if submitting separate pull requests for both branches was the wrong thing to do, or if there are any other branches where I should make these changes, please let me know - I'm pretty new to GitHub workflows). The pull requests can be found at

https://github.com/mate-desktop/atril/pull/395
https://github.com/mate-desktop/atril/pull/396

The segfault is being caused by dereferencing of a pointer which is NULL due to no file being loaded. The changes I have submitted add checks for a NULL value to the code to prevent this. Note that there were quite a few places in the code (in shell/ev-window.c) where unchecked dereferences were being performed, including in the zoom-adjustment code which is relevant here, and so I have added checks to all of these places.

**Comment by sc0w** [comment]
Fixed:

in `master` with https://github.com/mate-desktop/atril/commit/82d6a871b48c5054c629c83612b60dba63e70cc9
in `1.22` with https://github.com/mate-desktop/atril/commit/807e54f51919de389c2824df6ccef41947c57911
in `1.20` with https://github.com/mate-desktop/atril/commit/e6eb371942f86b981851b131bcc9bf7127bc2762
