### ISSUE TITLE
Atril doesn't remember window size

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/atril#48]
Orginal report at fedora bugzilla.
https://bugzilla.redhat.com/show_bug.cgi?id=1026576

 D. Wagner 2013-11-04 20:34:02 EST

Description of problem:

Atril doesn't remember the size of the window that I last used to view the last document.  It always opens a window of the same size, and that default size is very small (possibly related to the fact that I have a large, 2560x1600 pixel display).

This is annoying.  It means that the first thing I have to do after opening a document in atril is grab the lower-right corner of the window and resize it to be larger.  That shouldn't be necessary.  I have to do this, for every single atril window I ever open.  It's darn annoying!

Evince didn't have this problem for me: I think it must have been remembering the previous window size from the last invocation of evince, so I only had to resize evince once and then it would remember that for me, or something.  However it worked, I got large-sized windows when using evince and didn't have to constantly resize every single evince window I ever opened.  So, atril is a step backwards for me, compared to evince.

(Yes, I have been using Edit >> Save Current Settings as Default in the atril menus, but this does not cause atril to remember the size of the window when opening a new PDF document.)

For discussion of this in evince, see e.g.

https://mail.gnome.org/archives/evince-list/2005-August/msg00025.html

as well as

https://bugzilla.gnome.org/show_bug.cgi?id=606090
https://bugzilla.redhat.com/show_bug.cgi?id=626410

I don't get any errors on stderr when running atril on the command line.

Version-Release number of selected component (if applicable):

mate-document-viewer-1.6.1-6.fc19.x86_64
mate-desktop-1.6.2-0.5.git81c245b.fc19.x86_64
dbus-1.6.12-1.fc19.x86_64
dbus-glib-0.100-5.fc19.x86_64
gvfs-1.16.3-2.fc19.x86_64

confirmed by raveit65

**Comment by bcostescu** [comment]
I realize that this issue is almost 2 years old, but I have the same problem, on Fedora 21 x86_64 using the latest stable release as packaged in atril-1.10.2-1.fc21 (native Fedora package).

The information requested by stefano-k is:
$ gsettings list-recursively org.mate.Atril.Default
org.mate.Atril.Default window-ratio (2.1924666509861899, 1.6472684085510689)
org.mate.Atril.Default continuous true
org.mate.Atril.Default fullscreen false
org.mate.Atril.Default show-toolbar true
org.mate.Atril.Default show-sidebar false
org.mate.Atril.Default inverted-colors false
org.mate.Atril.Default zoom 1.0
org.mate.Atril.Default sidebar-page 'thumbnails'
org.mate.Atril.Default sidebar-size 132
org.mate.Atril.Default dual-page false
org.mate.Atril.Default sizing-mode 'best-fit'

I also use a 2560x1440 display, with 96x96 dots per inch (as reported by xdpyinfo). The window size is 600x600 (without windows decorations) and is independent of starting from the command line or from another application (f.e. Thunderbird).

Please let me know if I can provide further information.
