### ISSUE TITLE
Wrongly using libxml2 APIs can cause Dos and system crash

### ISSUE THREAD

**Issue by Zero0one1** [mate-desktop/atril#485]
Hi, developers:
We found a few bugs in the source code of atril(version a4f8d785f4).

## 1.missing xmlDocGetRootElement() check

According to [ API documentation](http://www.xmlsoft.org/html/libxml-tree.html#xmlDocGetRootElement) , The return value of `xmlDocGetRootElement` might be `NULL`, if we don't check for this, and dereference the pointer. it may cause a `segmentation fault`.

For example in `backend/epub/epub-document.c:184` 

It doesn't check if `htmltag` is `NULL` and dereference  by `htmltag->xmlChildrenNode` directly, so null dereference can happen.

```cpp
 184     htmlNodePtr htmltag = xmlDocGetRootElement(htmldoc);
 185     int count=0;
 186     htmlNodePtr bodytag = htmltag->xmlChildrenNode;
```

The whole list of source code related to this problem:

```cmd
backend/epub/epub-document.c:184
cut-n-paste/toolbar-editor/egg-toolbars-model.c:723
cut-n-paste/toolbar-editor/egg-toolbars-model.c:693
cut-n-paste/toolbar-editor/egg-toolbars-model.c:629
cut-n-paste/toolbar-editor/egg-toolbars-model.c:599
```

## 2. missing xmlFree() after xmlNodeGetContent()

According to the [libxml Documentation](http://www.xmlsoft.org/html/libxml-tree.html) , it's up to the caller to free the returned memory of `xmlNodeGetContent()`  with `xmlFree()`. If missing the `xmlFree()`, it might cause a DoS.

For example, `backend/pdf/ev-poppler.cc:541` doesn't free the memory allocated by `xmlNodeGetContent()` using `xmlFree()` . 

This bug results in memory leak. In some cases, the memory consumption might be huge, which may cause the process to corrupt. 

```cpp
 538             if (xpathObj != NULL) {
 539                 if (xpathObj->nodesetval != NULL &&
 540                     xpathObj->nodesetval->nodeNr != 0)
 541                     license->text = (gchar *)xmlNodeGetContent (xpathObj->nodesetval->nodeTab[0]);
 542                 xmlXPathFreeObject (xpathObj);
 543             }
```

The whole list of source code related to this problem:

```cmd
backend/pdf/ev-poppler.cc:541
backend/pdf/ev-poppler.cc:556
backend/pdf/ev-poppler.cc:569
backend/pdf/ev-poppler.cc:581
```

**Comment by rbuj** [comment]
2nd point: license->text is freed at:
https://github.com/mate-desktop/atril/blob/009aef5586de021292fc365969e763a98be53a75/libdocument/ev-document.c#L875

**Comment by Zero0one1** [comment]
Thanks for your quick reply. We looked into `atril/libdocument/ev-document.c#L875` (version 009aef5) and found it doesn’t work for 2nd point. Here is our detailed analyses. Could you point out if we are wrong?

1. `libdocument/ev-document.c#L875  g_free (license->text);` lies in the function `ev_document_license_free (EvDocumentLicense *license)`, which is called 3 times:

- `libdocument/ev-document.c#L835`(not related to 2nd point)

- `libdocument/ev-document.c#L841`(we skip it)

- `backend/pdf/ev-poppler.cc#L588`(only free `license` when 3 elements of it are NULL)

Then we analyze every potential path.


2. `libdocument/ev-document.c#L835` lies in the function `ev_document_info_free (EvDocumentInfo *info)`

https://github.com/mate-desktop/atril/blob/009aef5586de021292fc365969e763a98be53a75/libdocument/ev-document.c#L820-L835

Then this function is called at 2 place:
https://github.com/mate-desktop/atril/blob/009aef5586de021292fc365969e763a98be53a75/libdocument/ev-document.c#L785
and `libdocument/ev-document.c#L129`
```cpp
103: static void
104: ev_document_finalize (GObject *object)
105: {
106: 	EvDocument *document = EV_DOCUMENT (object);
...
129: 		ev_document_info_free (document->priv->info);
```
We have little idea about the first appearance, so we just look into the second deeper.
The function `ev_document_finalize(GObject *object)` appears at L163. Function `ev_document_class_init` is the end of this path and this path has no relationship with 2nd point.
https://github.com/mate-desktop/atril/blob/009aef5586de021292fc365969e763a98be53a75/libdocument/ev-document.c#L154-L164

3.  `libdocument/ev-document.c#L841` doesn't seem related to 2nd point.

4. The last one is `backend/pdf/ev-poppler.cc#L588`, which only frees `license` when 3 elements of it are NULL
https://github.com/mate-desktop/atril/blob/009aef5586de021292fc365969e763a98be53a75/backend/pdf/ev-poppler.cc#L587-L590

From what we see, `libdocument/ev-document.c#L875  g_free (license->text);` doesn't work for 2nd point.

**Comment by cwendling** [comment]
> Thanks for your quick reply. We looked into `atril/libdocument/ev-document.c#L875` (version [009aef5](https://github.com/mate-desktop/atril/commit/009aef5586de021292fc365969e763a98be53a75)) and found it doesn’t work for 2nd point. Here is our detailed analyses. Could you point out if we are wrong?
> 
>     1. `libdocument/ev-document.c#L875  g_free (license->text);` lies in the function `ev_document_license_free (EvDocumentLicense *license)`, which is called 3 times:
> 
> 
>     * `libdocument/ev-document.c#L835`(not related to 2nd point)

It is closely related, the allocation you're mentioning is happening in a function that returns an `EvDocumentLicense` object, which sole caller is a few lines down and stores it in a `EvDocumentInfo` -- which that line 835 relates to, it's the code that releases `EvDocumentInfo` memory.

> […]
> The function `ev_document_finalize(GObject *object)` appears at L163. Function `ev_document_class_init` is the end of this path and this path has no relationship with 2nd point.

It has, because that assigns `ev_document_finalize` at that GObject class's `finalize` method, which is called as part of the deallocation process of an `EvDocument` object.
And if you look closely, where is `pdf_document_get_info()` called? `pdf_document_get_info()` is the caller of `pdf_document_parse_metadata()` which itself calls `pdf_document_get_license_from_metadata()` and stores its value in a `EvDocumentInfo` field -- which `pdf_document_get_info()` returns, so we have a known and checkable path down to there.  So if we can trace where that function is called from, we should be good. So let's do that: it's actually defined as the `get_info()` implementation for `PdfDocumentClass`'s parent `EvDocumentClass` method (here `PdfDocumentClass` is a subclass of `EvDocumentClass`).  So, let's look at `EvDocumentClass::get_info()`'s callers.  The only caller is `_ev_document_get_info()`, which in turn is only called by `ev_document_load()`… which stores the returned `EvDocumentInfo` in the `priv->info` field of `EvDocument` -- the same `EvDocument` whose memory is released by `ev_document_finalize()`, which does call `ev_document_info_free()` on that very field as you noted yourself.

I guess three things lead you not to find the whole path:
* likely unfamiliarity with GObject and its allocation and deallocation mechanisms.  I'd recommend you look at [its documentation](https://developer.gnome.org/gobject/stable/gtype-instantiable-classed.html#gtype-instantiable-classed-init-done) to get a better grasp on it.
* possibly overlooking a couple of function *assignments* for function *calls*.
* IMO, going at it the wrong way; you should try and work your way up, so from `pdf_document_get_license_from_metadata()` to `pdf_document_parse_metadata()` to `pdf_document_get_info()` to `pdf_document_class_init()` which assigns that previous function as a member of and instance of `EvDocumentClass`.  Then, from there work out what calls this, and so forth.  Admittedly, familiarity with GObject and overall object-oriented programming in C helps, though.

Anyway, my take on this is that it's all fine, there's no leek.  The only nitpick there could be is that this memory gets freed with `g_free()` rather than `xmlFree()`, but in this case it's extremely likely to be calling the same memory allocator, so it should be fine.
